# Generated by Django 4.1.5 on 2023-01-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devtool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
                ('kind', models.CharField(blank=True, max_length=64)),
                ('content', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='region',
            new_name='interest',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
